### ISSUE TITLE
Astronomer Cloud: Platform Metrics

### ISSUE THREAD

**Issue by pcmaffey** [astronomerio/astronomer#89]
Users can see top-level metrics from deployments and usage.

**Comment by benjamingregory** [comment]
### Reminder
Create an issue in astro-cli when this is completed.

### Possible metrics to include
- [ ] Tasks rolled up on dag level
- [ ] Success/Failure (of task/dag)
- [ ] Average Time Run (by task/dag)
- [ ] Average Resources Used (by task/dag)

### Possible CLI behavior
#### Filtering:
- [ ] By DAG_ID (`astro airflow stats -d EXAMPLE_PIPELINE`)
- [ ] By Time (`astro airflow stats -t hour`)
- [ ] By Owner (`astro airflow stats -u MY_USER`)
#### Tailing:
- [ ] `astro airflow stats -f` (Default to polling every X seconds)
### Export
- [ ] `astro airflow stats -o CSV` (Outputs result to CSV)

**Comment by gregbrunk** [comment]
I think many of the ideas/tasks that @benjamingregory listed may also have overlap with this: 
- Epic (Airflow Logs): https://github.com/astronomerio/astronomer/issues/86

However, both tickets are being closed temporarily in favor of keeping all non-WIP issues (0.4+) out of GH until execution begins: https://astronomer.aha.io/epics/ORBIT-E-10
